### ISSUE TITLE
Create example for static config files

### ISSUE THREAD

**Issue by davidthor** [architect-team/architect-cli#195]
We had an issue opened, https://github.com/architect-team/architect-cli/issues/190#issuecomment-625880122, that was a proposal for a spec to better support file inputs for services, but we realized that the spec isn't needed and can be solved via the syntax in one of the comments which is as follows:

```yaml
# Service config
name: architect/api
parameters:
  PROPERTIES_FILE:
command: echo $PROPERTIES_FILE > /properties/default.properties && npm start
```

We need a running example of this to show how someone would implement it in practice. I would suggest something simple like an nginx service to show how it would be implemented. Please put the working sample in the `examples` directory.
