### ISSUE TITLE
Replacement for value_from syntax

### ISSUE THREAD

**Issue by davidthor** [architect-team/architect-cli#202]
Our `value_from` references have gotten us a long way, but have become a bit clunky and limiting in the way referencing can be done. We'd like to take inspiration from other CI/CD tools to provide a better, more scalable syntax for referring to parameters and dependencies.

# Proposal

After reviewing several different language syntaxes and tools that instrument variable replacement, we've landed on implementing a solution comparable to Github Actions with their [context and expression syntax](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions). This contextual referencing affords us the ability to handle reference contexts in unique ways. For example, referring to in-service parameters doesn't require network calls, but validating references to dependencies does.

We'd like to implement something similar with three starting "contexts":

### 1. interfaces

The first of these contexts is `interfaces` - the ability to reference the internal/external host, port, protocol, etc of each interface on a service.

```yaml
name: architect/test
interfaces:
  main: 8080
  admin:
    port: 8081
parameters:
  PUBLIC_ADDR: ${ interfaces.main.external.url }
  ADMIN_PRIVATE_ADDR: ${ interfaces.admin.internal.protocol }://${ interfaces.admin.internal.host }:${ interfaces.admin.internal.port }
```

### 2. parameters

The next context is the ability to reference other parameters. This can be very useful for creating composed parameters like the `DSN` below, and will be additionally useful when we eventually support parameters pass-through to dependencies (not part of this ticket):

```yaml
name: architect/test
parameters:
  DB_USER:
  DB_PASS:
  DB_NAME:
  DSN: postgres://${ parameters.DB_USER }:${ parameters.DB_PASS }@127.0.0.1:5432/${ parameters.DB_NAME }
```

### 3. dependencies

The final, and possibly most used context is `dependencies`. This is the ability to reference the contexts of ones dependencies. This will be important largely to be able to retrieve the interface context of a dependency (e.g. host/port):

```yaml
name: architect/test
dependencies:
  postgres/postgres: 11
  payments: architect/payments:latest
parameters:
  DB_ADDR: ${ dependencies['postgres/postgres'].interfaces.internal.url }
  PAYMENTS_API_ADDR: ${ dependencies.payments.interfaces.internal.url }
```

_Note: Dependencies are referenced by the dictionary key of the dependencies block for this service. Today, we only support keys that are the name of the dependency itself (changing that is not in scope for this ticket), but we should be aware that we may want to allow devs to change the key-name that they are referencing for a) ease of reading, and b) ability to include multiple references to the same dependency (e.g. two postgres instances)._

## Parsing details

* As part of a reference, you may access context information using one of two syntaxes.
   * Index syntax: github['sha']
   * Property dereference syntax: github.sha
* The prefix and suffix for all references are `${` and `}` respectively
* We should support references with and without spaces inside the prefix/suffix:
   * `${ parameters.DB_NAME }` and `${parameters.DB_NAME}` should both evaluate the same
* Context references should be ~~**validated on registration**, and~~ **resolved on deployment**.
