### ISSUE TITLE
Making sense of service interfaces

### ISSUE THREAD

**Issue by davidthor** [architect-team/architect-cli#203]
Months ago we came upon the use-case of a service listening on multiple ports – each with a different API and use-case for it's consumption. A simple example of this can by found in Ory's oauth service, [Hydra](https://www.ory.sh/hydra/), which has both a public and admin process running on two different ports from the same container.

In an effort to provide first-class support for this use-case, we introduced `interfaces` to service specs and required that each unique listener on a service get it's own interfaces. We similarly required that upstream consumers of the service cite which interface they wish to connect to when making calls to dependencies. An example of this can be found below:

```yaml
# downstream service
name: test/downstream
interfaces:
  public: 8080
  admin: 8081

# upstream service
name: test/upstream
interfaces:
  main: 80
dependencies:
  test/downstream: latest
parameters:
  DOWNSTREAM_PUBLIC_ADDR:
    value_from:
      dependency: test/downstream
      interface: public
      value: $HOST:$PORT
```

While the spec above works well, it beckons the question of whether or not a downstream service really has N interfaces or if it really has 1. Should a service have multiple distinct contracts that it exposes independently, or does it have a single contract with multiple rules. While the current implementation reflects the logistics of operating two processes from the same container, is that reflection the best way to expose the service's contract to consumers or is it simply an implementation detail?

# What do we hope to solve

In order to achieve portability of services, we must find the lines between service creator and operator that allow them both to act autonomously. Before we can accomplish that, we must outline what problems we want to solve and the ways someone can design a service that we want to maintain:

1. Listen for traffic on one or more ports
2. Allow traffic using one or more protocols
3. Allow for debuggers to be attached on a port locally
4. Map incoming requests to different service paths (path rewrites)
5. Configure throughput or limits on incoming payloads (e.g. body size, timeout length, JWT verification, etc.)
6. Send traffic to the service from another using a supported protocol

We'll be spending the coming days coming up with as many use-cases as possible for brokering the relationship between publisher and consumer so as to ensure an upcoming proposals for work account for these use-cases. Stay tuned and expect a proposal shortly!
