### ISSUE TITLE
Updates to component spec

### ISSUE THREAD

**Issue by davidthor** [architect-team/architect-cli#224]
In recent weeks we've been noodling on how we can best public vs. private services, generalized networking rules, and component interfaces to make it easier to create portable application components. One of the critical things we've found to be important in order to accommodate and encapsulate all the features we hope a component to contain is to switch to a model where a component can contain N services instead of 1. 

Having components be 1:1 equivalent to a single service or runtime is forcing developers to split their application in ways they don't find natural, and inhibiting them from controlling component ingress in a graceful fashion that is separate from their service runtimes. For this reason, we're going to make the following changes:

* Rename Services in our registry to Components
* Add a `services` block inside component specs (previously service specs) where N services can be described
* Move all service runtime properties into the new `services` block to be associated with the corresponding runtime

### Frontend, backend, database (current)

```yaml
# database spec
name: architect/database
image: postgres:11
interfaces:
  postgres: 5432
parameters:
  ROOT_DB_USER:
    default: architect
  ROOT_DB_PASS:
    required: true
environment:
  POSTGRES_USER: ${ parameters.ROOT_DB_USER }
  POSTGRES_PASSWORD: ${ parameters.ROOT_DB_PASS }
volumes:
  pgdata:
    mount_path: /var/lib/postgresql/data/pgdata

# backend spec
name: architect/backend
image: architect/backend:latest
interfaces:
  public: 8080
  admin: 8081
dependencies:
  architect/database: latest
parameters:
  DB_USER:
    default: architect
  DB_PASS:
    required: true
  DB_NAME:
    default: architect
environment:
  DB_ADDR: postgres://${ parameters.DB_USER }:${ parameters.DB_PASS }@${ dependencies['architect/database'].interfaces.postgres.host }:${ dependencies['architect/database'].interfaces.postgres.port }/${ parameters.DB_NAME }

# frontend spec
name: architect/frontend
image: architect/frontend:latest
dependencies:
  architect/backend: latest
environment:
  BACKEND_ADDR: ${ dependencies['architect/backend'].interfaces.public.url }
```

The problems with the above include:

1. The database in particular is important to make private. No one else should be accessing it, but since it still has to be registered as a service with Architect in order to be instrumented in deployments.
2. Even though the API can be shared, the team creating it may not have a need for it to be shared and independently accessible. However, they're still forced to create a new config and describe it separately instead of as a bundle.

### Frontend, backend, database (new)

With the new component specification, we hope to make a stack like the one shown above much easier to instrument by sharing a resource type:

```yaml
name: architect/stack
parameters:
  ROOT_DB_USER:
    default: architect
  ROOT_DB_PASS:
    required: true
  API_DB_USER:
    default: ${ parameters.ROOT_DB_USER }
  API_DB_PASS:
    default: ${ parameters.ROOT_DB_PASS }
  API_DB_NAME:
    default: architect
interfaces: 
  web:
    description: Exposes the frontend upstream to outside traffic
    url: ${ services.frontend.interfaces.web.url }
services:
  db:
    image: postgres:11
    interfaces:
      postgres: 5432
    environment:
      POSTGRES_USER: ${ parameters.ROOT_DB_USER }
      POSTGRES_PASSWORD: ${ parameters.ROOT_DB_PASS }
    volumes:
      pgdata:
        mount_path: /var/lib/postgresql/data/pgdata
  backend:
    image: architect/backend:latest
    interfaces:
      public: 8080
      admin: 8081
    environment:
      DB_ADDR: postgres://${ parameters.API_DB_USER }:${ parameters.API_DB_PASS }@${ services.db.interfaces.postgres.host }:${ services.db.interfaces.postgres.port }/${ parameters.API_DB_NAME }
  frontend:
    image: architect/frontend:latest
    interfaces:
      web: 8080
    environment:
      BACKEND_ADDR: ${ services.backend.interfaces.public.url }
```

With the above syntax, our entire application is represented as a single component spec. The services it includes share parameters and metadata, and are guaranteed to be deployed privately as a bundle. `dependencies` is still a top-level field that can be used to refer to required peer components, but only full components will be registered with Architect's registry to be cited as dependencies – not individual services. This helps us establish an easy way to represent uniquely bundled services and a way to privately allocate services that are intended to be privately attached to by a parent (like databases).
