### ISSUE TITLE
Dynamic credentialing

### ISSUE THREAD

**Issue by davidthor** [architect-team/architect-cli#225]
One of the things we've learned while working with users that want to store application credentials in secret managers is the value of dynamic secrets in respect to application portability. Dynamic secret generation can make it so that parallel environments can be deployed with unique application credentials without forcing the environment operator to manually provision the credentials. So long as there exists a dynamic credential that issues unique access for each request, parallel environments can be deployed and each will be issued its own set of credentials. 

What we'd like to do with Architect is provide first-class support for dynamic credentials in our component spec – enabling component creators to both describe dynamic credentials that a service can make available to consumers, and automatically enrich services with credentials dynamically issued with each deployment. This two sided relationship would make it significantly easier for components to be automatically deployed as they would no longer need credentials to be manually created and allocated in advance of the deployment. 

As part of this discuss, we first want to outline the use cases we have in mind directly so that we can design the feature to support all cases. The use-cases we have in mind are below, and we're actively looking for others:

1. Provisioned services
   * includes databases and other services that get deployed privately to each environment and require credentials for access to sensitive, stateful data
2. Hosted services
   * Includes identity services, payments, notification systems, and any other SaaS API services that have permanent resolvable addresses

### WIP example spec

Below is a work-in-progress component spec that shows how a service would register dynamic credentials and how another service would consume them. 

```yaml
name: architect/dynamic-credentials
parameters:
  ROOT_DB_USER:
    default: architect
  ROOT_DB_PASS:
    required: true
credentials:
  postgres:
    description: |
      Returns a JSON object containing a unique username/password combo used to access this
      postgres instance
    # the image that will be used to execute the credential command
    image: postgres:11
    # A command that will generate a new credential
    command: |
      NEW_USER=randomString()
      NEW_PASS=randomString()
      PGPASSWORD=${ parameters.DB_ROOT_PASS }
      psql -U ${ parameters.DB_ROOT_USER } -c '\
        CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}'; \
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}"'; \
      '
      echo '{"username": "$NEW_USER", "password": "$NEW_PASS"}'
services:
  database:
    image: postgres:11
    ports:
      postgres: 5432
    environment:
      POSTGRES_USER: ${ parameters.ROOT_DB_USER }
      POSTGRES_PASSWORD: ${ parameters.ROOT_DB_PASS }
  api:
    image: architect/api:latest
    ports:
      main: 8080
    environment:
      # When this gets deployed, it will be issued a credential from the postgres instance
      DB_CREDENTIALS: ${ credentials.postgres() }
```

As you can see from the above, the service only needs to parameterize the root credentials and then all credentials for other services can be issued dynamically. This becomes exponentially more powerful with each consumer of a dynamic credential.

**Comment by davidthor** [comment]
Here's another example of what it would look like using a permanently hosted service like Auth0. Auth0 registers each application and requires them to use different client IDs and secrets. These credentials are also associated with some rules that can impact how Auth0 reacts to requests (e.g. the allowed redirect URIs after a successful login), which means the credentials need to be parameterized:

```yaml
name: architect/auth0
parameters:
  AUTH0_HOSTNAME:
    default: architect.auth0.com
  MANAGEMENT_API_KEY:
    description: |
      API key used to access Auth0's management API, which is used to create applications
    required: true
interfaces:
  auth0:
    backend:
      host: ${ parameters.AUTH0_HOSTNAME }
      port: 443
      protocol: https
credentials:
  application:
    description: Returns the client ID and secret for a new Auth0 application
    image: ubuntu:latest
    parameters:
      - name: CLIENT_NAME
         required: true
         description: |
           Friendly name of the client to create. If a matching name already exists, the
           matching client ID and secret will be returned.
      - name: ALLOWED_CALLBACKS
         description: |
           Comma-separated list of URLs whitelisted for Auth0 to use as a callback to the
           client after authentication.
      - name: ALLOWED_LOGOUT_URLS
         description: |
           Comma-separated list of URLs that are valid to redirect to after logout from Auth0.
           Wildcards are allowed for subdomains.
    command: |
      curl -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${ parameters.MANAGEMENT_API_KEY }" \
        -d '{"name": "$CLIENT_NAME", "callbacks": "$ALLOWED_CALLBACKS", "allowed_logout_urls": "$ALLOWED_LOGOUT_URLS"}' \
        https://${ parameters.AUTH0_HOSTNAME }/api/v2/clients
```

Now any service that wants to connect to auth0 can cite the auth0 component as a dependency dynamically be issued application credentials on each deploy. Each service in the component below will get unique credentials

```yaml
name: architect/dynamic-credentials
dependencies:
  architect/auth0: latest
services:
  api:
    image: architect/api:latest
    ports:
      main: 8080
    environment:
      AUTH0_CREDENTIALS: ${ dependencies['architect/auth0'].credentials.application('api-${ architect.environment_name }') }
  frontend:
    image: architect/frontend:latest
    ports:
      web: 8080
    environment:
      AUTH0_CREDENTIALS: ${ dependencies['architect/auth0'].credentials.application('frontend-${ architect.environment_name }') }
```
