### ISSUE TITLE
Interface path rewrites

### ISSUE THREAD

**Issue by davidthor** [architect-team/architect-cli#233]
One of the problems we've consistently run into making apps portable, specifically in regards to client-side webapps like SPAs and static sites, is the need for one service to be exposed to external traffic in order to power another. Since client-side applications make requests from a browser to their backend, the backend **always** needs to be accessible to the same degree as the webserver. Since Architect currently only supports a 1:1 relationship between an interface and a service it connects to, there is no way for a component creator to force two services to be exposed at the same time. This in turn means that operators are naively able to expose just a webapp to outside traffic without the backend being accessible thus causing the component to fail. 

In order to allow component creators to make their components easier to use, we'd like for them to have a way to assert that two services need to be accessible as a unit. Our proposal below aims to solve this problem by allowing interfaces to include rules that dictate when traffic should be forwarded to one service over another. The first set of available rules will be path rewrites to support http traffic flows:

```yaml
name: examples/path-rewrites

services:
  backend:
    interfaces:
      http: 8080
  frontend:
    interfaces:
      web: 8081

interfaces:
  webapp:
    description: Interface exposing both the webapp and the backend to upstream traffic on the same domain.
    rules:
      - path: /
         url: ${ services.frontend.interfaces.web.url }
      - path: /api/
         url: ${ services.backend.interfaces.http.url }
```

The interfaces block above includes a new field, `rules`, that allows developers to specify path-based rewrite logic dictating that traffic should be forwarded to different services based on the URL prefix. What this would mean in practice is that the frontend service will always be able to resolve its backend counterpart on a relative address, `/api/*`, whenever the stack is deployed by Architect. Architect will instrument the necessary API gateways and configure them appropriately to ensure that traffic resolves to each service respectively.
