### ISSUE TITLE
Issue using Host Overrides with new interface spec

### ISSUE THREAD

**Issue by mueschm** [architect-team/architect-cli#836]
**Describe the bug**
If you attempt to override a `url` while you have an `ingress` block then we fail spec validation.

**To Reproduce**
```
name: test

secrets:
  override:
    required: false

services:
  test:
    image: nginxdemos/hello:latest
    interfaces:
      auth:
        url: ${{ secrets.override }}
        port: 80
        ingress:
          subdomain: 'test'
```
If you comment out `url`, then it works. Though if you leave it in its broken.

**Expected behavior**
Host overrides should work with ingress.
